
-- Seed demo investors (user_id is nullable, so no FK issue)
INSERT INTO public.investors (name, firm, bio, focus_domains, stage_preference, ticket_size_min, ticket_size_max, location, past_investments) VALUES
('Rohit Sharma', 'AngelX Ventures', 'Angel investor focused on AI and FinTech startups in India. 25+ investments across early-stage companies.', ARRAY['AI', 'FinTech', 'SaaS'], ARRAY['Pre-seed', 'Seed'], 500000, 5000000, 'Mumbai, India', '[{"name": "PayEase", "amount": 2000000}, {"name": "DataMind AI", "amount": 1500000}]'::jsonb),
('Priya Patel', 'SeedFund Capital', 'Early-stage VC partner with expertise in EdTech and HealthTech. Former CTO at a unicorn startup.', ARRAY['EdTech', 'HealthTech', 'DeepTech'], ARRAY['Seed', 'Series A'], 2000000, 20000000, 'Bangalore, India', '[{"name": "LearnFlow", "amount": 5000000}, {"name": "MedAssist", "amount": 8000000}]'::jsonb),
('Vikram Desai', 'Horizon Partners', 'Growth-stage investor with 15+ years in venture capital. Focus on B2B SaaS and marketplace models.', ARRAY['SaaS', 'Marketplace', 'B2B'], ARRAY['Series A', 'Series B'], 10000000, 50000000, 'Delhi, India', '[{"name": "CloudSync", "amount": 15000000}, {"name": "TradeHub", "amount": 25000000}]'::jsonb),
('Ananya Krishnan', 'WomenFirst Fund', 'Champion of women-led startups. Invested in 40+ companies across consumer tech and sustainability.', ARRAY['Consumer Tech', 'Sustainability', 'D2C'], ARRAY['Pre-seed', 'Seed'], 300000, 3000000, 'Chennai, India', '[{"name": "GreenBasket", "amount": 1000000}, {"name": "StyleBox", "amount": 2000000}]'::jsonb),
('Rajesh Iyer', 'TechBridge Ventures', 'Deep tech investor and ex-Google engineer. Passionate about AI/ML, blockchain, and Web3 innovations.', ARRAY['AI', 'Blockchain', 'Web3'], ARRAY['Seed', 'Series A'], 1000000, 10000000, 'Hyderabad, India', '[{"name": "ChainLedger", "amount": 3000000}, {"name": "NeuralOps", "amount": 7000000}]'::jsonb),
('Meera Joshi', 'Impact Capital', 'Social impact investor focused on rural tech, AgriTech, and financial inclusion startups.', ARRAY['AgriTech', 'FinTech', 'Social Impact'], ARRAY['Pre-seed', 'Seed'], 200000, 2000000, 'Pune, India', '[{"name": "FarmConnect", "amount": 800000}, {"name": "PayLocal", "amount": 1500000}]'::jsonb);
