// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgbuphpufacjkcjquupd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhnYnVwaHB1ZmFjamtjanF1dXBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg2Mzc0ODUsImV4cCI6MjA4NDIxMzQ4NX0.wBukNtj0UwtfMi5ZwhTXOheNDNyDt_znVZ9jDjbv_Jw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});